In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

1. 데이터 불러오기
------------

In [12]:
passengers = pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')
passengers.head(3)
print(passengers.shape)
print(passengers.head())

(887, 8)
   Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500  


2. 데이터 전처리하기
------------

In [28]:
passengers['Sex'] = passengers['Sex'].map({'female':1,'male':0})
#여성이 살아남을 확률이 높을 것 같으니 남성을 0, 여성을 1로 지정

In [15]:
passengers['Age'].fillna(value=passengers['Age'].mean(), inplace=True)
#데이터를 보면 Age값이 비어있는 경우가 있다. 이 경우 평균값으로 대체

In [16]:
passengers['FirstClass'] = passengers['Pclass'].apply(lambda x: 1 if x == 1 else 0)
passengers['SecondClass'] = passengers['Pclass'].apply(lambda x: 1 if x == 2 else 0)


In [29]:
#Pclass의 경우 1등석,2등석 구분해주는 feature로 만들어주기위해 컬럼 새로 생성

In [17]:
features = passengers[['Sex', 'Age', 'FirstClass', 'SecondClass']]
survival = passengers['Survived']

3. 데이터 분리하기
---------

In [18]:
from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(features, survival)


4. 데이터 정규화(스케일링)하기
-------

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

5. 모델 생성 및 평가하기
-------

In [20]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(train_features, train_labels)

LogisticRegression()

In [30]:
#데이터 넣어주고 fit 해주면 끝

In [21]:
print(model.score(train_features, train_labels))

0.7879699248120301


In [31]:
#train data로 정확도를 찍어봤고, 79%정도 맞췄다고 한다.

In [22]:
print(model.score(test_features, test_labels))

0.8108108108108109


In [32]:
#test data에서도 확인해볼수 있다. 81% 정도 맞춤

In [23]:
print(model.coef_)

[[ 1.14967026 -0.50908962  1.10091587  0.53604533]]


In [33]:
#각 feature들의 계수(coefficient)를 확인해본다. 어떤 feature가 생존에 큰 영향을 주는가

5. 예측하기
------

In [24]:
import numpy as np
Jack = np.array([0.0, 20.0, 0.0, 0.0])
Rose = np.array([1.0, 17.0, 1.0, 0.0])
ME = np.array([0.0, 24.0, 1.0, 0.0])
sample_passengers = np.array([Jack, Rose, ME])

In [35]:
#새로운 데이터 (내 정보를 넣어보자)
#24살 남자 1등석 탔다고 지정

In [25]:
sample_passengers = scaler.transform(sample_passengers)

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [36]:
#스케일링 진행

In [37]:
print(model.predict(sample_passengers))

[0 1 1]


In [38]:
#로즈와 나는 생존

In [27]:
print(model.predict_proba(sample_passengers))

[[0.88668044 0.11331956]
 [0.04617638 0.95382362]
 [0.40876255 0.59123745]]


In [39]:
#생존확률도 확인해 볼 수 있다. 60%정도 되기에 생존이라고 예측!!